sequential_topology:
  left_right_neighbors:
    left: None
    right: 13.52.254.62
  
  global_routing_table:
    "001": self
    "002": right
    "003": right
    "004": right
    "005": right
    "006": right
    "007": right
    "008": right
